### ISSUE TITLE
unit test

### ISSUE THREAD

**Issue by bichikim** [typescript-korea/nuxt-typescript-realworld-example-app#16]
- mocha + cahi + @vue/test-utils 어떨까요 ?

**Comment by gloriaJun** [comment]
전 jest + @vue/test-utils 만 사용해봤는데...
전 머든 좋습니다!!!!

**Comment by bichikim** [comment]
넵!

**Comment by bichikim** [comment]
mocha +chai unit test 구성

**Comment by gloriaJun** [comment]
적용해주시면, 단위테스트 작성해보면서 기술을 습득해보도록 하겠습니다!!
