### ISSUE TITLE
travis CI를 이용해서 빌드 연동을 하면 될까요?

### ISSUE THREAD

**Issue by gloriaJun** [typescript-korea/nuxt-typescript-realworld-example-app#18]
travis ci를 이용해서 설정해두면 되려나요??
그리고 github gh-pages와 같은 브랜치로 데모페이지를 연결해두면 현재 master 브랜치에 대한 진행 사항도 전반적으로 공유도 되고 할 것 같은데..

어떻게 생각하세요???
(아..너무 두서없이 작성한 것도 같네요)

**Comment by bichikim** [comment]
괌갔다 왔습니다 ㅋㅋㅋㅋ 그래서 답변이 늦어 졋네요.

**Comment by bichikim** [comment]
네 해야될 부분 입니다.

**Comment by bichikim** [comment]
travis CI 를 이용하여 하는 것에 찬성 합니다.

**Comment by gloriaJun** [comment]
흠..그렇다면, 제가 nuxt만 공부할 겸해서 별도로  realworld 기반으로 이것저것 연동해봤거든요.
참고해봐주세요~이렇게 저희 하고 있는 플젝에도 반영하면 될런지~~
그렇다면 이번 주 중에 진행할 수 있는 부분에 대해서 설정 후 PR 보내볼게요~~

https://github.com/gloriaJun/vue2-nuxt-realworld-example-app

**Comment by bichikim** [comment]
@gloriaJun 네 보겠습니다. 감사합니다. !
