### ISSUE TITLE
이슈 드리블

### ISSUE THREAD

**Issue by Vallista** [typescript-korea/nuxt-typescript-realworld-example-app#21]
안녕하세요. 회사에서 context switching 이슈로 인해 웹쪽을 볼 시간이 없어서 늦어진 점 죄송합니다.

다름이 아니라 최근 다시 진행하게 되어 이슈 코멘트를 남기게 되었습니다.

1. Folder Structure base 및 File Name 이슈

베이스로 잡고가는 것이 뭔지 몰라서 https://github.com/gothinkster/vue-realworld-example-app 를 참고하여 스트럭쳐나 File Name을 따라가려 하는데 혹시 따로 고민하신 것이 있나 의견이 궁금합니다.

2. DevOps

DevOps의 경우 TravisCI or Circle CI, 혹은 Jenkins 등의 선택지가 있는데 Travis CI로 가시는 건지 의견이 궁금합니다.

또한 저번에 오프라인 미팅에서 야살님이 말씀해주신 것도 고려해보면 좋겠습니다.

3. Project 사용 제안

제가 몇 주간 typescript를 바쁘다는 핑계로 보지 않은 것을 반성하며 (...) Github Projects를 사용하여 Development Cycle을 주기적으로 잡아보는게 어떤가 하는 생각이 들었습니다. 

피드백 감사드립니다.

**Comment by gloriaJun** [comment]
@Vallista , @bichikim 

**2. DevOps** 
Travis CI는 제가 언급을 한 부분이라서..제가 첨언(?)을 하자면...
꼭 Travis로 갈 필요는 없습니다. 단지, ci/cd 관련 설정이 필요한데.....어떻게 할까요? 라는 내용이긴했고..
아직 어느 도구를 이용하여 진행할 지는 결정된 것은 없는 것 같아요.

**3. Project 사용 제안**
github projects를 이용해서  dev cycle 주기적으로 잡아보는 것 도 좋을 것 같습니다.
그리고 각자의 일감을 나누어서 작업하는 것은 어떨까요???? 좀 더 책임감도 가져가게 되지 않을까요??

**Comment by bichikim** [comment]
@Vallista @bichikim 
1. 파일 네임 까지 따라 하는건 생각못했네요 좋은 생각입니다.
2. Travis 좋지요
3. 네 그렇게 해요!

**Comment by bichikim** [comment]
다만 [vue-realworld-example-app store](https://github.com/gothinkster/vue-realworld-example-app/tree/master/src/store) 부분에 actons.type.js 에 타입이 죄다 모여 있는 것이 보기엔 별로네요.
