### ISSUE TITLE
element-ui 도입?

### ISSUE THREAD

**Issue by bichikim** [typescript-korea/nuxt-typescript-realworld-example-app#5]
element-ui를 사용할가요?

**Comment by bichikim** [comment]
제공하는게 있네요 저걸 써야 하는 걸까요 
근데 실프로젝트는 미리정의 된 컴포넌트 셋을 쓰는 경우가 많아서요

**Comment by gloriaJun** [comment]
실 프로젝트는 미리 정의된 컴포넌트를 사용하거나, 퍼블리셔가 제공하는 것을 쓰기도 하죠.
혹시나 싶어서 저는 일단 미리 제공되는게 있다고 말씀을 드린거고...

제공되는 것을 쓸 지 아니면 element-ui와 같은 컴포넌트 셋을 사용할지에 대해서는 다른 분들 의견도 들어보는게 좋을 것 같아요..^^

**Comment by bichikim** [comment]
네 마져요 그런데 저기 리얼월드 프로젝트 모두? 저 템플릿을 섰네요 우리도 써야 하나 싶기도요

**Comment by gloriaJun** [comment]
가이드에 나온 것과 별개로 angular, vue, react로 작성된 다른 realworld 프로젝트들이 제공되는 템플릿으로 구현을 하고, 컴포넌트 구현 방식이나 signup 이전/이후에 대한 동작들에 대해서만 각자 구현 방식의 차이가 있는 것 처럼 보여요~~

일단 저희도 프로젝트 진행은 해야하고, 다른 프로젝트가 가는 방향에 어느 정도는 구색을 맞춰 가는게 좋을 것도 싶네요~~

해당 이슈는 어느 정도 마무리를 해야하지 않을까 해서 제가 생각하는 바를 추가로 적어봤어요~~~

**Comment by bichikim** [comment]
네 저도 그렇게 생각합니다.
